# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
###########################
#        General          #
###########################
title: Suskins Services
headerStyle: underlined
hideVersion: true
useEqualHeights: true
hideErrors: false
target: _blank
cardBlur: xl
iconStyle: theme
color: slate
theme: dark
bookmarksStyle: icons
disableCollapse: true

###########################
#      QuickLaunch        #
###########################
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false

###########################
#         Layout          #
###########################
layout:
  Developer:
    icon: mdi-code-json
    tab: First
    header: false
    style: row
    columns: 6
  Media Server:
    icon: mdi-play-pause
    tab: First
    style: row
    columns: 4
  Docker Server:
    icon: si-docker
    tab: First
    style: row
    columns: 4
  Monitoring Server:
    icon: mdi-chart-multiple
    tab: First
    style: row
    columns: 4
  Development Server:
    icon: mdi-code-json
    tab: First
    style: row
    columns: 4
  General:
    icon: mdi-server
    tab: First
    style: row
    columns: 4
