---
username: docker
puid: 1000
pgid: 1000
base_dir: /home/docker/server-docker

containers:
  - grocy
  - mealie
  - postgres
  - pubgolf_postgres
  - pubgolf_backend
  - pubgolf_frontend
  - cloudflare-ddns
  - byte_stash
  - adguard
