---
- name: README - Aggregate services from all hosts
  ansible.builtin.include_tasks:
    file: "../tasks/core/aggregate_services.yml"

- name: README - Generate README.md
  ansible.builtin.template:
    src: ../config/readme/README.md.j2
    dest: "{{ playbook_dir }}/README.md"
  vars:
    all_services: "{{ (static_services | default([])) + (all_docker_services | default([])) }}"
  delegate_to: localhost
