---
- name: CLEANUPARR - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  loop:
    - "{{ base_dir }}/cleanuparr"

- name: CLEANUPARR - Create container
  community.docker.docker_container:
    name: cleanuparr
    image: ghcr.io/cleanuparr/cleanuparr:2.5.1
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "11011:11011"
    volumes:
      - "{{ base_dir }}/cleanuparr:/config"
    env:
      PUID: "{{ puid | string }}"
      PGID: "{{ pgid | string }}"
      TZ: "{{ timezone }}"

- name: CLEANUPARR - Define service entry
  ansible.builtin.set_fact:
    cleanuparr_entry:
      name: cleanuparr
      host: "cleanuparr.{{ domain }}"
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 11011
      scheme: http
      secured: true
      homepage: true
      healthcheck: true
      proxied: true

- name: CLEANUPARR - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services + [cleanuparr_entry] }}"
