---
- name: GITHUB-RUNNER - Create directory and permissions
  ansible.builtin.file:
    path: "{{ base_dir }}/github-runner"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: GITHUB-RUNNER - Create container
  community.docker.docker_container:
    name: github-runner
    image: myoung34/github-runner:latest
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    volumes:
      - "{{ base_dir }}/github-runner:/runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      ACCESS_TOKEN: "{{ GITHUB_RUNNER_TOKEN }}"
      RUNNER_SCOPE: "repo"
      REPO_URL: "https://github.com/BenSuskins/homelab-ansible-plays"
      RUNNER_NAME: "self-hosted"
      RUNNER_WORKDIR: "/runner/_work"
      LABELS: "docker,homelab,development"
      DISABLE_AUTO_UPDATE: "false"

- name: GITHUB-RUNNER - Define service entry
  ansible.builtin.set_fact:
    github_runner_entry:
      name: github-runner
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"

- name: GITHUB-RUNNER - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services + [github_runner_entry] }}"
