---
- name: HUNTARR - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  loop:
    - "{{ base_dir }}/huntarr"

- name: HUNTARR - Create container
  community.docker.docker_container:
    name: huntarr
    image: ghcr.io/plexguide/huntarr:9.2.3
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "9705:9705"
    volumes:
      - "{{ base_dir }}/huntarr:/config"
    env:
      TZ: "{{ timezone }}"

- name: HUNTARR - Define service entry
  ansible.builtin.set_fact:
    huntarr_entry:
      name: huntarr
      host: "huntarr.{{ domain }}"
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 9705
      scheme: http
      secured: true
      healthcheck: true
      healthcheck_path: /api/health
      homepage: true
      proxied: true

- name: HUNTARR - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services + [huntarr_entry] }}"
