---
- name: OPEN BOOKS - Create container
  community.docker.docker_container:
    name: open-books
    image: evanbuss/openbooks:4.5.0
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "8080:80"
    volumes:
      - "/mnt/media/books:/books"
    command: --persist -n CupcakeCreator

- name: OPENBOOKS - Define service entry
  ansible.builtin.set_fact:
    openbooks_entry:
      name: openbooks
      host: openbooks.suskins.co.uk
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 8080
      scheme: http
      secured: true
      homepage: true

- name: OPENBOOKS - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services + [openbooks_entry] }}"
