---
- name: PROFILARR - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  loop:
    - "{{ base_dir }}/profilarr"

- name: PROFILARR - Create container
  community.docker.docker_container:
    name: profilarr
    image: santiagosayshey/profilarr:v1.1.3
    restart_policy: always
    restart: true
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "6868:6868"
    volumes:
      - "{{ base_dir }}/profilarr:/config"
    env:
      PUID: "{{ puid | string }}"
      PGID: "{{ pgid | string }}"
      TZ: "{{ timezone }}"

- name: PROFILARR - Define service entry
  ansible.builtin.set_fact:
    profilarr_entry:
      name: profilarr
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 6868
      scheme: http
      secured: true
      hidden: false

- name: PROFILARR - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ (docker_services | default([])) + [profilarr_entry] }}"
