---
- name: PUBGOLF-FRONTEND - Create container
  community.docker.docker_container:
    name: pubgolf-frontend
    image: ghcr.io/bensuskins/pubgolf-frontend:93cd9f5
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "3003:3000"
    env:
      NEXT_PUBLIC_API_URL: "https://api.pubgolf.me"

- name: PUBGOLF - Define service entry
  ansible.builtin.set_fact:
    pubgolf_entry:
      name: pubgolf
      host: pubgolf.suskins.co.uk
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 3003
      scheme: http
      secured: false

- name: PUBGOLF - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services + [pubgolf_entry] }}"
