---
- name: POSTGRES - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  loop:
    - "{{ base_dir }}/pubgolf-postgres"

- name: POSTGRES - Create Container
  community.docker.docker_container:
    name: pubgolf-postgres
    image: postgres:17-alpine
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "5433:5432"
    volumes:
      - "{{ base_dir }}/pubgolf-postgres/pgdata:/var/lib/postgresql/data"
    env:
      POSTGRES_USER: "{{ DB_USERNAME }}"
      POSTGRES_PASSWORD: "{{ DB_PASSWORD }}"
      POSTGRES_DB: "pubgolf"

- name: PUBGOLF-POSTGRES - Define service entry
  ansible.builtin.set_fact:
    pubgolf_postgres_entry:
      name: pubgolf-postgres
      host: "pubgolf-postgres.{{ domain }}"
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 5433
      scheme: http
      secured: false

- name: PUBGOLF-POSTGRES - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services + [pubgolf_postgres_entry] }}"
