---
- name: SHELFMARK - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  loop:
    - "{{ base_dir }}/shelfmark"

- name: SHELFMARK - Create container
  community.docker.docker_container:
    name: shelfmark
    image: ghcr.io/calibrain/shelfmark:v1.0.3
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "8084:8084"
    volumes:
      - "{{ base_dir }}/shelfmark:/config"
      - "/mnt/media/books:/books"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ puid | string }}"
      PGID: "{{ pgid | string }}"

- name: SHELFMARK - Define service entry
  ansible.builtin.set_fact:
    shelfmark_entry:
      name: shelfmark
      host: "shelfmark.{{ domain }}"
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 8084
      scheme: http
      secured: true
      healthcheck: true
      homepage: true
      proxied: true

- name: SHELFMARK - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services + [shelfmark_entry] }}"
