---
- name: TRACEARR - Create directory and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  loop:
    - "{{ base_dir }}/tracearr"
 
- name: TRACEARR - Create container
  community.docker.docker_container:
    name: tracearr
    image: ghcr.io/connorgallopo/tracearr:supervised
    restart_policy: always
    state: started
    pull: true
    networks:
      - name: homelab
    ports:
      - "3000:3000"
    volumes:
      - "{{ base_dir }}/tracearr:/data"
    env:
      TZ: "{{ timezone }}"
 
- name: TRACEARR - Define service entry
  ansible.builtin.set_fact:
    tracearr_entry:
      name: tracearr
      host: "tracearr.{{ domain }}"
      ip: "{{ inventory_hostname }}"
      friendly_name: "{{ friendly_name }}"
      port: 3000
      scheme: http
      secured: true
      healthcheck: true
      healthcheck_path: /health
      homepage: true
      proxied: true
 
- name: TRACEARR - Append to docker_services
  ansible.builtin.set_fact:
    docker_services: "{{ docker_services + [tracearr_entry] }}"