name: Clean Homelab

on:
  workflow_dispatch:

jobs:
  clean:
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Create vault password file
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASS }}" > ~/.ansible_vault_pass
          chmod 600 ~/.ansible_vault_pass

      - name: Run Ansible
        run: |
          ansible-playbook plays/clean.yml --vault-password-file ~/.ansible_vault_pass
