name: Update Homelab

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Checkout secrets repo
        uses: actions/checkout@v6
        with:
          repository: bensuskins/secrets
          path: secrets
          token: ${{ secrets.SECRETS_REPO_TOKEN }}
  
  update-secrets:
    runs-on: self-hosted
    needs: [checkout]
    steps:
      - name: Move vault file
        run: |
          mkdir -p ~/.ansible
          mv secrets/vault.yml ~/.ansible/vault.yml
  
  run-ansible:
    runs-on: self-hosted
    needs: [checkout, update-secrets]
    steps:
      - name: Run Ansible
        run: |
          ansible-playbook plays/update.yml --vault-password-file ~/.ansible_vault_pass
